### PR TITLE
Feat: track the expense

### PR DESCRIPTION
**Pull request by aleksanderboe**

### CODE REVIEW

**Comment by sree-hari-s** [comment]
what happend I was actually reviewing your work.

**Comment by aleksanderboe** [comment]
> what happend I was actually reviewing your work.

I can reopen, but i saw someone else wanting to work on this.

**Comment by PuruSinghvi** [comment]
Hey @aleksanderboe , thanks a lot for letting me work on this feature. I am new to open-source contributions and really appreciate you letting me do this task!

**Comment by sree-hari-s** [comment]
Closing this as @PuruSinghvi has completed the task. Thankyou for your contribution @aleksanderboe.

**Pull request closed without merging**
