### PR TITLE
Created retirement_goals_tracker.py

### PR DESCRIPTION
**Pull request by kharshita590**

### CODE REVIEW

**Comment by sree-hari-s** [comment]
there is no point in creating a separate application, try to modify the frontend to utilize this function currently, Streamlit is being used.

If you have an idea about Flask or Django you can implement that way because I am planning to expand this application

**Review by sree-hari-s — CHANGES_REQUESTED** [review]
https://github.com/sree-hari-s/Expense-Tracker/pull/10#issuecomment-1755883995

**Comment by kharshita590** [comment]
@sree-hari-s ohkay

**Comment by kharshita590** [comment]
@sree-hari-s but where is the frontend part?

**Comment by sree-hari-s** [comment]
Closing this PR as this is not planned

**Pull request closed without merging**
