### PR TITLE
Regarding family member, check if exists and add a method to manages …

### PR DESCRIPTION
**Pull request by navascogt**
…(update_family_member). Update other code lines to be PEP8 compliant.

### CODE REVIEW

**Comment by navascogt** [comment]
After changing to avoid family member duplicates, it seems that the list is not updated in the main page, maybe could be another issue to add and assign to me too ;-), meanwhile I research how to do it in streamlit or if you give me a clue how to do that.

Another concern, is that the new update function use the class as a parameter to avoid to read and search again in the function, if use the same behavior that the add function that just receives the name not the class.

**Comment by sree-hari-s** [comment]
> After changing to avoid family member duplicates, it seems that the list is not updated in the main page, maybe could be another issue to add and assign to me too ;-), meanwhile I research how to do it in streamlit or if you give me a clue how to do that.
> 
> Another concern, is that the new update function use the class as a parameter to avoid to read and search again in the function, if use the same behavior that the add function that just receives the name not the class.

there are lot of issues like this when I initially thought about the expansion of this project. Might require a database setup. for all that checks.

**Comment by navascogt** [comment]
Yes @sree-hari-s , the data must be persistent!!! I think it can be another issue (feature) to add, but before confirming with you.

**Comment by sree-hari-s** [comment]
> Yes @sree-hari-s , the data must be persistent!!! I think it can be another issue (feature) to add, but before confirming with you.

Yeah thankyou for confirming

**Comment by sree-hari-s** [comment]
> Yes @sree-hari-s , the data must be persistent!!! I think it can be another issue (feature) to add, but before confirming with you.

then I think registration and login would be required ?

**Comment by navascogt** [comment]
This is my first contact with streamlit, but for both cases, be persistent and login are features that I saw can do it, I will add both issues and will assign to me in order to do that.  Do you agree with me?

**Comment by sree-hari-s** [comment]
> This is my first contact with streamlit, but for both cases, be persistent and login are features that I saw can do it, I will add both issues and will assign to me in order to do that. Do you agree with me?

Yeah I am also contributing and learning by collaboration its fine.

**Comment by sree-hari-s** [comment]
#13

**Review by sree-hari-s — APPROVED** [review]

**Pull request merged**
